config/routes.rb
Rails.application.routes.draw do
  root 'sessions#dashboard'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  resources :projects
  resources :time_entries
  resources :developers

  get 'developers/edit' => 'developers#edit'

end

app/models/developer.rb
class Developer < ActiveRecord::Base
  has_secure_password
  has_many :time_entries
  belongs_to :project
  validates :email, presence: true
  validates :email, uniqueness: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_entries
  has_many :developers, through: :time_entries

  def hours_worked
    time_entries.sum(:duration)
  end
  def overtime
    hours_worked > allowed_hours
  end
end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :developer
  belongs_to :project
  validates :duration, presence: true
  validates :developer_id, presence: true
  validates :project_id, presence: true

  def work_week
    time_entries.where(date:
      (beginning_of_week..end_of_week)
    ).sum(:duration)
  end
  def out_of_time
    work_week > 40
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def logged_in?
    redirect_to login_path, notice: "You must log in to access this page" unless session[:user_id]
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :logged_in?
  def index
    @developers = Developer.all
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      redirect_to developers_path, notice: 'Developer was succesfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @developer.destroy
      redirect_to developers_path, notice: 'Developer was successfully destroyed'
  end


  def show
  end

  def update
    if @developer.update(developer_params)
      redirect_to developers_path, notice: 'Developer was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @developer = Developer.new
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_developer
    @developer = Developer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def developer_params
    params.require(:developer).permit(:id, :name, :email, :password, :password_digest)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :logged_in?
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: 'Project was succesfully created.'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end
  def destroy
    @project.destroy
      redirect_to projects_path, notice: 'Project was successfully destroyed'
  end
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :allowed_hours)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def dashboard
  end
  def new
  end
  def create

    @developer = Developer.find_by(email: params[:email])
    if @developer && @developer.authenticate(params[:password])
      session[:user_id] = @developer.id
      redirect_to developers_path, notice: "You have succesfully logged in!"
    else
      flash.now[:alert] = "Login failed: invalid email or password."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You have logged out."
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :logged_in?

  def new
    @time_entry = TimeEntry.new
  end

  def create
    @time_entry = TimeEntry.new(time_entry_params)
    if @time_entry.save
      redirect_to time_entries_path, notice: 'Time Entry was successfully created.'
    else
      render :new
    end
  end

  def delete
    @time_entry.destroy
      redirect_to time_entries_path, notice: 'Time Entry was successfully destroyed.'
  end

  def index
    @time_entries = TimeEntry.all
  end

  def show
  end

  def update
    if @time_entry.update(time_entry_params)
      redirect_to time_entries_index_path, "Time Entry was successfully updated."
    else
      render :index
    end
  end

  private
    def set_time_entry
      @time_entry = TimeEntry.find(params[:id])
    end

    def time_entry_params
      params.require(:time_entry).permit(:duration, :date, :developer_id, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developers/destroy.html.erb
<h1>Developers#destroy</h1>
<p>Find me in app/views/developers/destroy.html.erb</p>

app/views/developers/edit.html.erb
<h1>Editing Developer</h1>

<%= render 'form' %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="bar">
  <li>
    <%= link_to "Manage Projects", projects_path %>
    <%= link_to "View your Time Entries", time_entries_path %>
    <%= link_to "View Developers", developers_path %>
  </li>
</nav>
<h1>Listing Developers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.name %></td>
        <td><%= developer.email %></td>
        <td><%= developer.password_digest %></td>
        <td><%= link_to 'Show', developer %></td>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'form' %>


<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<div class="links">
 <%= link_to "Home", developers_path %>
</div>

app/views/developers/update.html.erb
<h1>Developers#update</h1>
<p>Find me in app/views/developers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class=container>
    <header>
     <nav class = "header">
       <p id = "logout"><%= link_to 'Logout', logout_path %></p>
     </nav>
    </header>

<%= yield %>

    <footer>
       <nav class = "footer">
          <div class = "footer-left-links">
            <ul>
          
            </ul>
          </div>
       </nav>
    </footer>
  </div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="name_field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="allowed_hours_field">
    <%= f.label :allowed_hours %><br>
    <%= f.text_field :allowed_hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<nav class="bar">
  <li>
    <%= link_to "Manage Projects", projects_path %>
    <%= link_to "View Time Entries", time_entries_path %>
    <%= link_to "View Developers", developers_path %>
  </li>
</nav>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr class="tablelable">
      <th>Project Name</th>
      <th> Allowed Hours</th>
      <th> Hours Worked</th>
      <th> Developer Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr class="tableright">
        <td><%= project.name %></td>
        <td><%= project.allowed_hours %></td>
        <td><%= project.hours_worked %></td>

        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path %>

app/views/time_entries/_form.html.erb
<%= form_for(@time_entry) do |f| %>
  <% if @time_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_entry.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @time_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="duration_field">
    <%= f.label :duration %>
    <%= f.text_field :duration %>
  </div>
  <div class="date_field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>
  <div class="developer_field">
    <%= f.label :developer %>
    <%= f.collection_select :developer_id, Developer.all, :id, :name %>
  </div>
  <div class="project_field">
    <%= f.label :project %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing Time Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_entry %> |
<%= link_to 'Back', time_entries_path %>

app/views/time_entries/index.html.erb
<p id="notice"><%= notice %></p>

<nav class=bar>
  <li>
    <%= link_to "Manage Projects", projects_path %>
    <%= link_to "View Time Entries", time_entries_path %>
    <%= link_to "View Developers", developers_path %>
  </li>
</nav>

<h1>Listing Time Entries</h1>

<table>
  <thead>
    <tr class=tablelable>
      <th>Project ID</th>
      <th>Project Name</th>
      <th>Time Entry Date</th>
      <th>Duration</th>
      <th>Developer Name</th>
      <th>Developer ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |time_entry| %>
      <tr class=tableright>
        <td><%= time_entry.project_id %></td>
        <td><%= time_entry.project.name %></td>
        <td><%= time_entry.date %></td>
        <td><%= time_entry.duration %></td>
        <td><%= time_entry.developer.name %></td>
        <td><%= time_entry.developer_id %></td>
        <td><%= link_to 'Show', time_entry %></td>
        <td><%= link_to 'Edit', edit_time_entry_path(time_entry) %></td>
        <td><%= link_to 'Destroy', time_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time entry', new_time_entry_path %>

app/views/time_entries/new.html.erb
<h1>New Time Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', time_entries_path %>

app/views/time_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @time_entry.project_id %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @time_entry.developer_id %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @time_entry.duration %>
</p>

<p>
  <strong>Date:</strong>
  <%= @time_entry.date %>
</p>

<%= link_to 'Edit', edit_time_entry_path(@time_entry) %> |
<%= link_to 'Back', time_entries_path %>